version: '3.9'

services:
  bot:
    container_name: javaBot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - BOT_NAME=toxaencom1_first_bot
      - X_API_KEY=${X_API_KEY}
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_IP=${DB_IP}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - BOT_CRON=0 0 7 * * *
      - WEATHER_CRON=10 0 0 * * *
      - JAVA_TOOL_OPTIONS=-Duser.timezone=Asia/Aqtobe
    dns:
      - 8.8.8.8  # Google DNS
      - 8.8.4.4
    restart: unless-stopped