# variables taken from Program parameters (Intellij Idea)
spring:
  liquibase:
    enabled: true
  application:
    name: WeatherSender
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:mysql://localhost:3307/JavaRush
    username: ${db_username}
    password: ${db_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false

weatherAPI:
  url: https://www.meteosource.com/api/v1/free/point
  apiKey: ${X-API-Key}

bot:
  cron: 0 0/1 * * * * #0 0 7 * * *
  name: toxaecom1_first_bot
  token: ${bot_token}

weather:
  cron: 10 0 0 * * *