spring:
  liquibase:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false

  datasource:
    url: jdbc:mysql://localhost:3307/JavaRush
    username: ${db_username:mysql}
    password: ${db_password:mysql}
    driver-class-name: com.mysql.cj.jdbc.Driver

bot:
  cron: 0 0/1 * * * *

weather:
  cron: 10 0 0 * * *