# variables taken from Program parameters (Intellij Idea)
spring:
  application:
    name: WeatherSender
    version: 0.1.0
    ip: ${HOST_IP}
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}


weatherAPI:
  url: https://www.meteosource.com/api/v1/free/point
  apiKey: ${X-API-KEY}

bot:
  admin-chat-id: 365980032
  cron: ${BOT_CRON} #0 0/1 * * * * #0 0 7 * * *
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}

weather:
  cron: ${WEATHER_CRON} #10 0 0 * * *

relay:
  ip: ${RELAY_IP}
  delay-in-seconds: ${RELAY_DELAY}

connect:
  ssh:
    username: ${SSH_USERNAME}
    password: ${SSH_PASSWORD}