# variables taken from Program parameters (Intellij Idea)
spring:
  application:
    name: WeatherSender
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}


weatherAPI:
  url: https://www.meteosource.com/api/v1/free/point
  apiKey: ${X-API-Key}

default:
  cron:
    bot: 0 0/1 * * * *
    weather: 10 0 0 * * *

bot:
  cron: ${bot_cron} #0 0/1 * * * * #0 0 7 * * *
  name: ${bot_name}
  token: ${bot_token}

weather:
  cron: ${weather_cron} #10 0 0 * * *